import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Project, SiteLog, Permit } from '../supabase';

export async function generateWeeklyReport(
    project: Project,
    siteLogs: SiteLog[],
    permits: Permit[]
): Promise<Blob> {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString('en-MY');

    // Add Branding
    doc.setFontSize(22);
    doc.text('BinaPintar', 14, 20);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Smart Construction CMS', 14, 26);

    // Header Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Project Status Report: ${today}`, 140, 20, { align: 'left' });

    // Project Summary
    doc.setDrawColor(200);
    doc.line(14, 32, 196, 32);

    doc.setFontSize(16);
    doc.text(project.name, 14, 42);

    doc.setFontSize(10);
    doc.text(`Status: ${project.status}`, 14, 50);
    doc.text(`Start Date: ${new Date(project.start_date).toLocaleDateString()}`, 14, 56);
    if (project.end_date) {
        doc.text(`End Date: ${new Date(project.end_date).toLocaleDateString()}`, 80, 56);
    }

    // Site Logs Section
    doc.setFontSize(14);
    doc.text('Site Progress Logs (Last 7 Days)', 14, 70);

    const logData = siteLogs.map(log => [
        new Date(log.created_at).toLocaleDateString(),
        log.description,
        log.metadata?.latitude ? 'Location Verified' : 'Manual Entry'
    ]);

    autoTable(doc, {
        startY: 75,
        head: [['Date', 'Description', 'Verification']],
        body: logData,
        headStyles: { fillColor: [3, 105, 161] }, // Sky-700
        styles: { fontSize: 9 },
        columnStyles: { 0: { cellWidth: 30 }, 2: { cellWidth: 35 } }
    });

    // Upcoming Permits
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text('Upcoming Permit Expirations', 14, finalY);

    const permitData = permits.map(permit => [
        permit.doc_name,
        new Date(permit.expiry_date).toLocaleDateString(),
        getDaysRemaining(permit.expiry_date) + ' days'
    ]);

    autoTable(doc, {
        startY: finalY + 5,
        head: [['Document Name', 'Expiry Date', 'Days Remaining']],
        body: permitData,
        headStyles: { fillColor: [249, 115, 22] }, // Orange-500
        styles: { fontSize: 9 }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} - Generated by BinaPintar`, 196, 285, { align: 'right' });
    }

    return doc.output('blob');
}

function getDaysRemaining(dateStr: string): number {
    const expiry = new Date(dateStr);
    const today = new Date();
    const diffTime = expiry.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}
